spring:
  application:
    name: Vendor

  data:
    mongodb:
      uri: mongodb://localhost:27017/jobs

  mail:
    host: smtp.gmail.com
    port: 587
    username: mnatikarsagar@gmail.com
    password: gvjh ihtt xzxe oook
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000

# 🔷 AWS CONFIG (ADD THIS)
aws:
  secretKey: DoVaT5t4vQdKs0mDSL7NvgNEACYv9m9ryJAu5hpx
  region: ap-southeast-2   # Sydney (from your bucket)
  bucket: offer-letter-bucket-687159379135-ap-southeast-2-an

app:
  interview:
    base-url: http://localhost:4200/test/

  hr:
    email: vidya.sagar@hginfotech.io

interview:
  interviewers:
    - id: 1
      name: A
      email: vidyasagarnatikar07@gmail.com
    - id: 2
      name: B
      email: bramhananda.kl@hginfotech.io
    - id: 3
      name: C
      email: c@company.com
    - id: 4
      name: D
      email: d@company.com